### ISSUE TITLE
Discount code generator module

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#142]
### Description

A new module to generate discount codes

### Todo

- [x] Function to generate codes
- [x] CLI tool to get input from user
- [x] Save generated codes to file
- [x] Write documentation
