### ISSUE TITLE
Implement a complete package for parsing JSON products to CSV

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#325]
### Description

Implement a module to parse commercetools products from JSON format to CSV

(Part of a series implementing the rewrite of the [product-csv-sync](https://github.com/sphereio/sphere-node-product-csv-sync) module)

#292 is getting too large so will be broken down into smaller issues and smaller PRs, with this issue encompassing all the issues

### TODO

- [x] Implement core functionality(#292)

- [x] Implement CLI wrapper (#332)

- [x] Add integration tests (#332)

- [x] Add documentation
